package com.guild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Scholar generated by hbm2java
 */
@Entity
@Table(name = "scholar", catalog = "guilddb", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@NamedQueries({
	@NamedQuery(name="Scholar.findAll", query= "SELECT c FROM Scholar c ORDER BY c.registerDate DESC"),
	@NamedQuery(name="Scholar.findByEmail", query= "SELECT c FROM Scholar c where c.email=:email"),
	@NamedQuery(name="Scholar.countAll", query= "SELECT count(c) FROM Scholar c"),
	@NamedQuery(name="Scholar.checkLogin", query= "SELECT c FROM Scholar c WHERE c.email=:email AND c.password=:password")
})
public class Scholar implements java.io.Serializable {

	private int scholarId;
	private String email;
	private String fullname;
	private String address;
	private String city;
	private String country;
	private String phone;
	private String zipcode;
	private String password;
	private byte[] profilepic;
	private Date registerDate;

	public Scholar() {
	}

	public Scholar(int scholarId, String email, String fullname, String address, String city, String country,
			String phone, String zipcode, String password, byte[] profilepic, Date registerDate) {
		this.scholarId = scholarId;
		this.email = email;
		this.fullname = fullname;
		this.address = address;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.profilepic=profilepic;
		this.registerDate = registerDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "scholar_id", unique = true, nullable = false)
	public int getScholarId() {
		return this.scholarId;
	}

	public void setScholarId(int scholarId) {
		this.scholarId = scholarId;
	}

	@Column(name = "email", unique = true, nullable = false, length = 64)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fullname", nullable = false, length = 30)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "address", nullable = false, length = 128)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false, length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", nullable = false, length = 64)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "zipcode", nullable = false, length = 24)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Lob
	@Column(name = "profilepic", nullable = true, columnDefinition="mediumblob")
	public byte[] getProfilepic() {
		return this.profilepic;
	}

	public void setProfilepic(byte[] profilepic) {
		this.profilepic = profilepic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_date", nullable = false, length = 19)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}


}
